### ISSUE TITLE
Фикс блокировки mixed content если у вас сайт на HTTPS

### ISSUE THREAD

**Issue by Artmoneyse** [book777/monAJAX#5]
В конфиге config.php
Код:
`'dir' => 'http://'.$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF']).'/', // Путь к скрипту (лучше не менять)`
Лучше вообще не указывать протокол.
Если сайт открыт по https то и скрипт запросит по данному протоколу.
Код который должен выйти:
`'dir' => '//'.$_SERVER['HTTP_HOST'].dirname($_SERVER['PHP_SELF']).'/', // Путь к скрипту (лучше не менять)`

**Comment by malsatin** [comment]
Можете сделать PR?

**Comment by Artmoneyse** [comment]
Могу позже сделать форк, исправив все подобные проблемы.
