### ISSUE TITLE
Хостинг не поддерживает такую дешифрацию

### ISSUE THREAD

**Issue by MiXeR54** [book777/monAJAX#8]
beget.ru - хост
на локалке ответ есть, 
![localka](https://user-images.githubusercontent.com/26678374/63464838-bbec9e00-c468-11e9-8c79-8f5a93094442.jpg)

 на хосте ошибка
![Untitled](https://user-images.githubusercontent.com/26678374/63464891-ceff6e00-c468-11e9-9fd4-0d9244ce5a3b.png)

php-ver: 5.6 но пробовал и другие 7.1 и 5.3

**Comment by book777** [comment]
Вряд ли смогу помочь без доступа к FTP. Если согласишься предоставить, то telegram - @book777

**Comment by No4NaMe** [comment]
Если у вас хостинг регру попробуйте php73-bx

**Comment by book777** [comment]
Проблема в логике кода была https://github.com/book777/monAJAX/commit/a85b73c608987029b109e94d389a9cce494bcb86#diff-408323905e7bb37431908d006e08eb49R172
