### ISSUE TITLE
Неизвестное ядро

### ISSUE THREAD

**Issue by No4NaMe** [book777/monAJAX#9]
Мониторинг работал нормально вдруг стал писать "Неизвестное ядро" С чем связано pocketmine 1.14x

**Comment by book777** [comment]
Может тебе кто сервер обновил? Попробуй новую версию скрипта скачать (я там фиксил баг с "Неизвестное ядро")

**Comment by No4NaMe** [comment]
В новом скрипте страница в обще не отображается пустота

**Comment by No4NaMe** [comment]
> 
> 
> Может тебе кто сервер обновил? Попробуй новую версию скрипта скачать (я там фиксил баг с "Неизвестное ядро")

В новом скрипте страница в обще не отображается пустота

**Comment by No4NaMe** [comment]
Откатил ядро все равно такая же ситуация

**Comment by book777** [comment]
насколько я вижу всё работает
